---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - platform.lab.beancloud.io
  resources:
  - clouds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - platform.lab.beancloud.io
  resources:
  - clouds/finalizers
  verbs:
  - update
- apiGroups:
  - platform.lab.beancloud.io
  resources:
  - clouds/status
  verbs:
  - get
  - patch
  - update
